#!/bin/sh
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t ext4 /dev/sda /mnt

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

Welcome to LTP Linux

!
cd /mnt
./runltp -f syscalls,tracing -g output.html
poweroff -f
